create table zepto_analysis(
sku_id SERIAL PRIMARY KEY,
CATEGORY VARCHAR(120),
NAME VARCHAR(150) NOT NULL,
MRP NUMERIC(8,2),
DISCOUNTPERCENTAGE NUMERIC(5,2),
AVALIABLE_QUANTITY INTEGER,
discountedSellingPrice NUMERIC(8,2),
WEIGHTIN_GMS INTEGER,
OUTOFSTOCK BOOLEAN,
QUANTITY INTEGER
);

--exploring the zepto data
SELECT COUNT(*) FROM ZEPTO_ANALYSIS;
SELECT * FROM ZEPTO_ANALYSIS
LIMIT 10;
-- finding null values
SELECT * FROM ZEPTO_ANALYSIS
WHERE NAME IS NULL
OR 
CATEGORY IS NULL
OR
MRP IS NULL
OR
DISCOUNTPERCENTAGE IS NULL 
OR 
AVALIABLE_QUANTITY IS NULL
OR
discountedSellingPrice IS NULL
OR
WEIGHTIN_GMS IS NULL
OR
OUTOFSTOCK IS NULL
OR
QUANTITY IS NULL;
-- categories in dataset

SELECT DISTINCT CATEGORY
FROM ZEPTO_ANALYSIS
ORDER BY CATEGORY;
--finding outofstock products
SELECT OUTOFSTOCK,COUNT(SKU_ID)
FROM ZEPTO_ANALYSIS 
GROUP BY OUTOFSTOCK;
--stockkeeping units in dataset
SELECT NAME,COUNT(SKU_ID) AS "STOCK KEEPING UNITS"
FROM ZEPTO_ANALYSIS
GROUP BY NAME
HAVING COUNT(SKU_ID)>1
ORDER BY COUNT(SKU_ID) DESC;
--finding free or 0 products 
SELECT * FROM ZEPTO_ANALYSIS 
WHERE MRP=0 OR DISCOUNTEDSELLINGPRICE=0;
DELETE FROM ZEPTO_ANALYSIS
WHERE MRP=0;
--removing free or 0 products
UPDATE ZEPTO_ANALYSIS 
SET MRP=MRP/100.0,
DISCOUNTEDSELLINGPRICE=DISCOUNTEDSELLINGPRICE/100.0;
SELECT MRP,DISCOUNTEDSELLINGPRICE FROM ZEPTO_ANALYSIS


--1.WHICH PRODUCT HAS THE HIGHEST DISCOUNT
SELECT DISTINCT NAME,MRP,DISCOUNTEDSELLINGPRICE,DISCOUNTPERCENTAGE
FROM ZEPTO_ANALYSIS
ORDER BY DISCOUNTEDSELLINGPRICE DESC
LIMIT 20;

--2.WHAT ARE THE PRODUCT WITH HIGH MRP 
SELECT DISTINCT NAME,MRP
FROM ZEPTO_ANALYSIS
ORDER BY MRP DESC
LIMIT 10;

--3.WT ARE THE PRODUCT WITH HIGH MRP BUT OUTOFSTOCK
SELECT DISTINCT NAME,MRP
FROM ZEPTO_ANALYSIS
WHERE OUTOFSTOCK=TRUE AND MRP>300
ORDER BY MRP DESC;

--4.CALCULATE THE ESTIMATES REVENUE BY CATEGORY
SELECT CATEGORY,
SUM(discountedSellingPrice *AVALIABLE_QUANTITY) AS TOTAL_REVENUE
FROM ZEPTO_ANALYSIS
GROUP BY CATEGORY 
ORDER BY TOTAL_REVENUE  DESC;

--5.FIND ALL PRODUCTS WHERE MRP IS GREATER THAN 500 AND DISCOUNT IS LESS THAN 10%
SELECT DISTINCT NAME ,MRP,DISCOUNTPERCENTAGE

FROM ZEPTO_ANALYSIS
WHERE MRP>500 AND DISCOUNTPERCENTAGE <10
ORDER BY MRP DESC,DISCOUNTPERCENTAGE DESC;

--6.IDENTIFY THE TOP 5 CATEGORIES OFFERING THE HIGHEST AVG DISCOUNT PERCENTAGE
SELECT CATEGORY,
ROUND(AVG(DISCOUNTPERCENTAGE),2) AS AVG_DISCOUNT
FROM ZEPTO_ANALYSIS
GROUP BY CATEGORY
ORDER BY AVG_DISCOUNT DESC
LIMIT 5;
--7.group the products by category like low,medium,bulk
select  distinct name,weightin_gms,
case 
     when weightin_gms<1000 then 'low'
     when weightin_gms<5000 then 'medium'
	 else 'bulk'
end as weight_category
from zepto_analysis;
--8.wts the total inventory weight per category 
select category,
sum(weightin_gms*AVALIABLE_QUANTITY)AS TOTAL_WEIGHT
from zepto_analysis
group by category
order by total_weight DESC;





